//
// Created by timka on 23. 1. 2023.
//

#ifndef POSKOSEMESTRALNAPRACA_STAVPANACIKA_H
#define POSKOSEMESTRALNAPRACA_STAVPANACIKA_H
typedef enum stavPanacika{
    NEDEFINOVANY,
    JE_DOMA,
    JE_NA_STARTE,
    JE_NA_DRAHE,
    JE_V_CIELI,
} STAV_PANACIKA;
#endif //POSKOSEMESTRALNAPRACA_STAVPANACIKA_H
